### ISSUE TITLE
Not sure if this is something on my end

### ISSUE THREAD

**Issue by noods** [davatron5000/WP-Dribbble#3]
Warning: extract() [function.extract]: First argument should be an array in /home/thenoods/danhigbie.com/wp-content/plugins/WP-Dribbble/wp-dribbble.php on line 29

dribble displays fine with that line above it.

**Comment by davatron5000** [comment]
quick fix: delete line 29.

<del>extract($args);</del>

  it doesn't appear that its needed at all.
