### ISSUE TITLE
Cannot Modify Header Issue

### ISSUE THREAD

**Issue by tuhin** [davatron5000/WP-Dribbble#4]
Warning: Cannot modify header information - headers already sent by (output started at ...../wp-content/plugins/Dribbble/wp-dribbble.php:171) in ...../wp-admin/theme-editor.php on line 75
Some stupid whitespace issue. Though the plugin works fine but whenever I use some in built editor of wordpress to update my php files, this error pops up.

**Comment by davatron5000** [comment]
This is a whitespace bug and I've addressed it in the next patch that I'm testing.

QUICK FIX: delete the last blank line of wp-dribbble.php after the php close tag: ?>
