### ISSUE TITLE
Plugin could not be activated because it generated 1 characters of unexpected output

### ISSUE THREAD

**Issue by ronnyandre** [davatron5000/WP-Dribbble#5]
I get this error when trying to activate the plugin. Seems to be a WordPress 3.0 beta 2 issue.

**Comment by davatron5000** [comment]
i've just updated the plugin, but try and delete the last blank line of wp-dribbble.php and that should hopefully fix it.  if it does, could you let me know?  thanks.

**Comment by ronnyandre** [comment]
Yes the updated plugin works with WordPress 3 beta 2. I would presume it works with beta 1 as well. Thanks! :)
