### ISSUE TITLE
“Visit plugin site” URL is 404

### ISSUE THREAD

**Issue by splorp** [davatron5000/WP-Dribbble#6]
Clicking on the “Visit plugin site” link on the Manage Plugins page currently results in a 404 page. 

The current URL is:
http://daverupert.com/category/wordpress/wp-dribbble/

I’m assuming it should be:
http://daverupert.com/2010/05/dribbble-wordpress-plugin/

Cheers.

**Comment by davatron5000** [comment]
thanks.  should be fixed.

**Comment by splorp** [comment]
Great. Thank you.
